# Generated by Django 5.1.1 on 2024-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back', '0003_usuarionoregistrados_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
